<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import SearchInput from '@/components/molecules/SearchInput.vue'
import AppBadge from '@/components/atoms/AppBadge.vue'
import AppSpinner from '@/components/atoms/AppSpinner.vue'
import EmptyState from '@/components/molecules/EmptyState.vue'
import { useMouvementStore } from '@/stores/mouvement'
const store=useMouvementStore(); const search=ref(''); const movementId=ref('')
const movements=computed(()=>store.dashboard?.movements ?? (store.movement?[store.movement]:[]))
const filteredChildren=computed(()=>{const q=search.value.trim().toLowerCase();return !q?store.children:store.children.filter(c=>`${c.firstName} ${c.lastName}`.toLowerCase().includes(q)||c.parentLinks?.some(l=>`${l.parent.firstName} ${l.parent.lastName}`.toLowerCase().includes(q)) )})
async function load(){await store.loadChildren(movementId.value?{movementId:movementId.value}:undefined)}
onMounted(async()=>{await Promise.all([store.loadDashboard(),store.loadChildren()])}); watch(movementId,load)
</script>
<template><section class="space-y-6">
<header class="border-b border-[#C2BAB0] pb-5"><p class="eyebrow text-[#C25A34]">Gestion du mouvement</p><h1 class="page-title mt-1 text-3xl sm:text-4xl text-[#0B1F3A]">Enfants inscrits</h1><p class="mt-2 text-[#6B655D]">Consultez les enfants rattachés à vos mouvements et leurs responsables.</p></header>
<div class="grid gap-3 md:grid-cols-[minmax(0,1fr)_240px]"><SearchInput v-model="search" placeholder="Rechercher un enfant ou un parent…" /><select v-model="movementId" class="min-h-10 w-full border border-[#C2BAB0] bg-white px-3 text-sm"><option value="">Tous mes mouvements</option><option v-for="item in movements" :key="item.id" :value="item.id">{{item.name}}</option></select></div>
<div v-if="store.loading" class="flex min-h-40 items-center justify-center"><AppSpinner/></div>
<div v-else-if="filteredChildren.length" class="overflow-hidden border border-[#C2BAB0] bg-white"><div class="hidden overflow-x-auto md:block"><table class="w-full text-left text-sm"><thead class="border-b border-[#DDD7CF] bg-[#F7F5F2] text-xs uppercase tracking-wide text-[#6B655D]"><tr><th class="px-5 py-4">Enfant</th><th class="px-5 py-4">Mouvement</th><th class="px-5 py-4">Naissance</th><th class="px-5 py-4">Parents</th><th class="px-5 py-4">Contact</th></tr></thead><tbody><tr v-for="child in filteredChildren" :key="`${child.id}-${child.movement?.id??'all'}`" class="border-t border-[#EDE9E4]"><td class="px-5 py-4 font-semibold">{{child.firstName}} {{child.lastName}}</td><td class="px-5 py-4"><AppBadge>{{child.movement?.name??'—'}}</AppBadge></td><td class="px-5 py-4 text-[#6B655D]">{{child.birthDate?new Date(child.birthDate).toLocaleDateString('fr-FR'):'—'}}</td><td class="px-5 py-4">{{child.parentLinks?.length??0}}</td><td class="px-5 py-4 text-[#6B655D]">{{child.parentLinks?.[0]?.parent?.phone||child.parentLinks?.[0]?.parent?.email||'—'}}</td></tr></tbody></table></div><div class="divide-y divide-[#EDE9E4] md:hidden"><article v-for="child in filteredChildren" :key="child.id" class="p-5"><div class="flex items-start justify-between gap-3"><div><p class="font-semibold text-[#14345E]">{{child.firstName}} {{child.lastName}}</p><p class="mt-1 text-xs text-[#6B655D]">{{child.birthDate?new Date(child.birthDate).toLocaleDateString('fr-FR'):'Naissance non renseignée'}}</p></div><AppBadge>{{child.movement?.name??'—'}}</AppBadge></div><p class="mt-4 text-sm text-[#6B655D]">{{child.parentLinks?.length??0}} responsable(s)</p><p class="mt-1 text-sm">{{child.parentLinks?.[0]?.parent?.phone||child.parentLinks?.[0]?.parent?.email||'Contact non renseigné'}}</p></article></div></div>
<EmptyState v-else title="Aucun enfant trouvé" description="Aucun enfant ne correspond à la recherche actuelle."/>
</section></template>