import { Router } from 'express'
import { prisma } from '../lib/prisma'
import { authenticate } from '../middlewares/authenticate.middleware'
import { authorize } from '../middlewares/authorize.middleware'
import { requireParish } from '../middlewares/parish.middleware'
const router=Router()
router.use(authenticate,authorize('ADMIN_PARISH'),requireParish)
router.get('/',async(req,res,next)=>{try{const parishId=req.user!.parishId!;const q=String(req.query.q??'').trim();const people=await prisma.user.findMany({where:{parishId,status:'ACTIVE',...(q?{OR:[{firstName:{contains:q,mode:'insensitive'}},{lastName:{contains:q,mode:'insensitive'}},{phone:{contains:q,mode:'insensitive'}}]}:{})},select:{id:true,firstName:true,lastName:true,email:true,phone:true,faithfulProfile:{select:{birthDate:true}}},orderBy:[{lastName:'asc'},{firstName:'asc'}],take:50});const acts=await prisma.sacramentalAct.findMany({where:{parishId,...(q?{person:{OR:[{firstName:{contains:q,mode:'insensitive'}},{lastName:{contains:q,mode:'insensitive'}}]}}:{})},include:{person:{select:{id:true,firstName:true,lastName:true}}},orderBy:{celebrationDate:'desc'},take:100});res.json({success:true,data:{people,acts}})}catch(e){next(e)}})
router.post('/',async(req,res,next)=>{try{const parishId=req.user!.parishId!;const b=req.body??{};if(!b.personId||!b.type||!b.celebrationDate)return res.status(400).json({success:false,message:'Personne, sacrement et date sont obligatoires.'});const person=await prisma.user.findFirst({where:{id:b.personId,parishId}});if(!person)return res.status(404).json({success:false,message:'Personne introuvable.'});const item=await prisma.sacramentalAct.create({data:{parishId,personId:b.personId,type:b.type,celebrationDate:new Date(b.celebrationDate),place:b.place||null,celebrantName:b.celebrantName||null,registerNumber:b.registerNumber||null,certificateNumber:b.certificateNumber||null,notes:b.notes||null,annotations:b.annotations||null},include:{person:{select:{id:true,firstName:true,lastName:true}}}});res.status(201).json({success:true,data:item})}catch(e){next(e)}})
router.patch('/:id',async(req,res,next)=>{try{const parishId=req.user!.parishId!;const b=req.body??{};const item=await prisma.sacramentalAct.updateMany({where:{id:req.params.id,parishId},data:{...(b.status?{status:b.status}:{}),...(b.celebrationDate?{celebrationDate:new Date(b.celebrationDate)}:{}),...(b.place!==undefined?{place:b.place||null}:{}),...(b.celebrantName!==undefined?{celebrantName:b.celebrantName||null}:{}),...(b.registerNumber!==undefined?{registerNumber:b.registerNumber||null}:{}),...(b.certificateNumber!==undefined?{certificateNumber:b.certificateNumber||null}:{}),...(b.notes!==undefined?{notes:b.notes||null}:{}),...(b.annotations!==undefined?{annotations:b.annotations||null}:{})}});if(!item.count)return res.status(404).json({success:false,message:'Acte introuvable.'});res.json({success:true})}catch(e){next(e)}})
export default router
