import { Router } from 'express'
import { prisma } from '../lib/prisma'
import { authenticate } from '../middlewares/authenticate.middleware'
import { authorize } from '../middlewares/authorize.middleware'
import { requireParish } from '../middlewares/parish.middleware'
const router=Router()
router.use(authenticate,authorize('ADMIN_PARISH'),requireParish)
router.get('/',async(req,res,next)=>{try{const parishId=req.user!.parishId!;const items=await prisma.marriageCase.findMany({where:{parishId},orderBy:{celebrationDate:'asc'}});res.json({success:true,data:items})}catch(e){next(e)}})
router.post('/',async(req,res,next)=>{try{const parishId=req.user!.parishId!;const b=req.body??{};if(!b.groomName||!b.brideName||!b.celebrationDate)return res.status(400).json({success:false,message:'Les fiancés et la date sont obligatoires.'});const item=await prisma.marriageCase.create({data:{parishId,groomName:b.groomName.trim(),brideName:b.brideName.trim(),celebrationDate:new Date(b.celebrationDate),celebrationTime:b.celebrationTime||null,celebrantName:b.celebrantName?.trim()||null,status:b.status||'DRAFT',groomBirthDate:b.groomBirthDate?new Date(b.groomBirthDate):null,brideBirthDate:b.brideBirthDate?new Date(b.brideBirthDate):null,groomPhone:b.groomPhone?.trim()||null,bridePhone:b.bridePhone?.trim()||null,groomAddress:b.groomAddress?.trim()||null,brideAddress:b.brideAddress?.trim()||null,groomBaptismStatus:b.groomBaptismStatus||'PENDING',brideBaptismStatus:b.brideBaptismStatus||'PENDING',groomConfirmationStatus:b.groomConfirmationStatus||'PENDING',brideConfirmationStatus:b.brideConfirmationStatus||'PENDING',preparationStatus:b.preparationStatus||'PENDING',civilStatusStatus:b.civilStatusStatus||'PENDING',groomDocuments:Number(b.groomDocuments||0),brideDocuments:Number(b.brideDocuments||0),requiredDocuments:Number(b.requiredDocuments||3),publicationCount:Number(b.publicationCount||0),publication1Date:b.publication1Date?new Date(b.publication1Date):null,publication2Date:b.publication2Date?new Date(b.publication2Date):null,publication3Date:b.publication3Date?new Date(b.publication3Date):null,oppositionCount:Number(b.oppositionCount||0),oppositionNote:b.oppositionNote?.trim()||null,notes:b.notes?.trim()||null}});res.status(201).json({success:true,data:item})}catch(e){next(e)}})
router.patch('/:id',async(req,res,next)=>{try{const parishId=req.user!.parishId!;const b=req.body??{};const item=await prisma.marriageCase.updateMany({where:{id:req.params.id,parishId},data:{...(b.status?{status:b.status}:{}),...(b.groomName!==undefined?{groomName:String(b.groomName).trim()}:{}),...(b.brideName!==undefined?{brideName:String(b.brideName).trim()}:{}),...(b.groomBirthDate!==undefined?{groomBirthDate:b.groomBirthDate?new Date(b.groomBirthDate):null}:{}),...(b.brideBirthDate!==undefined?{brideBirthDate:b.brideBirthDate?new Date(b.brideBirthDate):null}:{}),...(b.groomPhone!==undefined?{groomPhone:b.groomPhone?.trim()||null}:{}),...(b.bridePhone!==undefined?{bridePhone:b.bridePhone?.trim()||null}:{}),...(b.groomAddress!==undefined?{groomAddress:b.groomAddress?.trim()||null}:{}),...(b.brideAddress!==undefined?{brideAddress:b.brideAddress?.trim()||null}:{}),...(b.groomBaptismStatus!==undefined?{groomBaptismStatus:b.groomBaptismStatus}:{}),...(b.brideBaptismStatus!==undefined?{brideBaptismStatus:b.brideBaptismStatus}:{}),...(b.groomConfirmationStatus!==undefined?{groomConfirmationStatus:b.groomConfirmationStatus}:{}),...(b.brideConfirmationStatus!==undefined?{brideConfirmationStatus:b.brideConfirmationStatus}:{}),...(b.preparationStatus!==undefined?{preparationStatus:b.preparationStatus}:{}),...(b.civilStatusStatus!==undefined?{civilStatusStatus:b.civilStatusStatus}:{}),...(b.groomDocuments!==undefined?{groomDocuments:Number(b.groomDocuments)}:{}),...(b.brideDocuments!==undefined?{brideDocuments:Number(b.brideDocuments)}:{}),...(b.publicationCount!==undefined?{publicationCount:Number(b.publicationCount)}:{}),...(b.publication1Date!==undefined?{publication1Date:b.publication1Date?new Date(b.publication1Date):null}:{}),...(b.publication2Date!==undefined?{publication2Date:b.publication2Date?new Date(b.publication2Date):null}:{}),...(b.publication3Date!==undefined?{publication3Date:b.publication3Date?new Date(b.publication3Date):null}:{}),...(b.oppositionCount!==undefined?{oppositionCount:Number(b.oppositionCount)}:{}),...(b.oppositionNote!==undefined?{oppositionNote:b.oppositionNote?.trim()||null}:{}),...(b.celebrationDate?{celebrationDate:new Date(b.celebrationDate)}:{}),...(b.celebrationTime!==undefined?{celebrationTime:b.celebrationTime||null}:{}),...(b.celebrantName!==undefined?{celebrantName:b.celebrantName||null}:{}),...(b.notes!==undefined?{notes:b.notes||null}:{})}});if(!item.count)return res.status(404).json({success:false,message:'Dossier introuvable.'});res.json({success:true})}catch(e){next(e)}})
export default router
