import { Router } from 'express'
import { prisma } from '../lib/prisma'
import { authenticate } from '../middlewares/authenticate.middleware'
import { authorize } from '../middlewares/authorize.middleware'
import { requireParish } from '../middlewares/parish.middleware'
const router=Router()
router.use(authenticate,authorize('ADMIN_PARISH'),requireParish)
router.get('/',async(req,res,next)=>{try{const parishId=req.user!.parishId!;const items=await prisma.communication.findMany({where:{parishId},include:{movement:{select:{id:true,name:true}},sender:{select:{firstName:true,lastName:true}},recipients:{select:{id:true,readAt:true}}},orderBy:{createdAt:'desc'}});res.json({success:true,data:items})}catch(e){next(e)}})
router.post('/',async(req,res,next)=>{try{const parishId=req.user!.parishId!,userId=req.user!.id;const b=req.body??{};if(!b.movementId||!b.title||!b.content)return res.status(400).json({success:false,message:'Mouvement, objet et message sont obligatoires.'});const movement=await prisma.movement.findFirst({where:{id:b.movementId,parishId},select:{id:true}});if(!movement)return res.status(404).json({success:false,message:'Mouvement introuvable.'});const users=await prisma.user.findMany({where:{parishId,status:'ACTIVE',movementMemberships:{some:{movementId:movement.id,status:'ACTIVE'}}},select:{id:true}});const parents=await prisma.user.findMany({where:{parishId,status:'ACTIVE',parentLinks:{some:{child:{registrations:{some:{movementId:movement.id}}}}}},select:{id:true}});const ids=new Set<string>();const audience=b.audience||'ALL';if(audience==='PARENTS')parents.forEach(u=>ids.add(u.id));else if(audience==='MEMBERS')users.forEach(u=>ids.add(u.id));else if(audience==='ALL'){users.forEach(u=>ids.add(u.id));parents.forEach(u=>ids.add(u.id));}else if(audience==='DONORS'){const donorPayments=await prisma.payment.findMany({where:{parishId,status:'SUCCESS',createdBy:{status:'ACTIVE'}},select:{createdById:true}});donorPayments.forEach(p=>{if(p.createdById)ids.add(p.createdById)});}if(!ids.size)return res.status(400).json({success:false,message:'Aucun destinataire actif.'});const scheduledAt=b.scheduledAt?new Date(b.scheduledAt):null;if(scheduledAt&&!Number.isFinite(scheduledAt.getTime()))return res.status(400).json({success:false,message:'Date de programmation invalide.'});const sendNow=b.sendNow===true;const item=await prisma.communication.create({data:{parishId,movementId:movement.id,senderId:userId,title:String(b.title).trim(),content:String(b.content).trim(),type:b.type||'ANNOUNCEMENT',status:sendNow?'SENT':'DRAFT',sentAt:sendNow?new Date():null,scheduledAt:sendNow?null:scheduledAt,recipients:{create:[...ids].map(userId=>({userId}))}},include:{movement:{select:{id:true,name:true}},recipients:{select:{id:true,readAt:true}}}});res.status(201).json({success:true,data:item})}catch(e){next(e)}})
export default router
