<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'
import { RefreshCw,Users,ClipboardList,WalletCards } from 'lucide-vue-next'
import { administrationActivityApi,type AdministrationActivity } from '@/services/administration-activity.service'
import { administrationMovementsApi,type AdministrationMovement } from '@/services/administration-movements.service'
const data=ref<AdministrationActivity|null>(null),movements=ref<AdministrationMovement[]>([]),loading=ref(true),error=ref(''),movementId=ref(''),days=ref(30)
const load=async()=>{loading.value=true;error.value='';try{data.value=await administrationActivityApi.get({movementId:movementId.value||undefined,days:days.value})}catch{error.value='Impossible de charger l’activité.'}finally{loading.value=false}}
onMounted(async()=>{try{movements.value=await administrationMovementsApi.list()}catch{} await load()})
const amount=computed(()=>new Intl.NumberFormat('fr-FR').format(data.value?.successfulPaymentsAmount??0)+' FCFA')
const dateLabel=(d:string)=>new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short'}).format(new Date(d))
</script>
<template>
<section class="space-y-6">
<header class="border border-[#C2BAB0] bg-white p-5 sm:p-7"><p class="eyebrow text-[#C25A34]">Supervision paroissiale</p><h1 class="page-title mt-2 text-3xl text-[#0B1F3A] sm:text-4xl">Activité des mouvements</h1><p class="mt-2 text-sm text-[#6B655D]">Suivi consolidé des inscriptions, membres et paiements.</p></header>
<div class="flex flex-col gap-3 sm:flex-row"><select v-model="movementId" @change="load" class="min-h-11 flex-1 border border-[#C2BAB0] bg-white px-3 text-sm"><option value="">Tous les mouvements</option><option v-for="m in movements" :key="m.id" :value="m.id">{{m.name}}</option></select><select v-model="days" @change="load" class="min-h-11 border border-[#C2BAB0] bg-white px-3 text-sm"><option :value="7">7 derniers jours</option><option :value="30">30 derniers jours</option><option :value="90">90 derniers jours</option></select><button @click="load" class="inline-flex min-h-11 items-center justify-center gap-2 border border-[#C2BAB0] bg-white px-4 text-sm font-semibold"><RefreshCw class="size-4" :class="loading?'animate-spin':''"/> Actualiser</button></div>
<div v-if="error" class="border border-[#B3261E]/30 bg-[#FFF5F4] p-4 text-sm text-[#B3261E]">{{error}}</div>
<div v-if="loading" class="border border-[#C2BAB0] bg-white p-6 text-sm text-[#6B655D]">Chargement...</div>
<template v-else-if="data">
<div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div class="border border-[#DDD7CF] bg-white p-4"><Users class="size-5 text-[#24548F]"/><p class="mt-2 text-xs font-semibold uppercase tracking-wide text-[#6B655D]">Membres actifs</p><p class="font-serif text-3xl text-[#14345E]">{{data.activeMembers}}</p></div><div class="border border-[#DDD7CF] bg-white p-4"><ClipboardList class="size-5 text-[#C25A34]"/><p class="mt-2 text-xs font-semibold uppercase tracking-wide text-[#6B655D]">Inscriptions</p><p class="font-serif text-3xl text-[#14345E]">{{data.registrationsCount}}</p></div><div class="border border-[#DDD7CF] bg-white p-4"><WalletCards class="size-5 text-[#14713C]"/><p class="mt-2 text-xs font-semibold uppercase tracking-wide text-[#6B655D]">Paiements réussis</p><p class="font-serif text-3xl text-[#14345E]">{{data.successfulPaymentsCount}}</p></div><div class="border border-[#DDD7CF] bg-white p-4"><p class="text-xs font-semibold uppercase tracking-wide text-[#6B655D]">Montant encaissé</p><p class="mt-2 font-serif text-2xl text-[#14345E]">{{amount}}</p></div></div>
<div class="grid gap-5 lg:grid-cols-2"><article class="border border-[#C2BAB0] bg-white p-5"><h2 class="page-title text-2xl text-[#14345E]">Inscriptions récentes</h2><div v-if="!data.recentRegistrations.length" class="mt-5 text-sm text-[#6B655D]">Aucune inscription sur la période.</div><div v-else class="mt-4 divide-y divide-[#EDE9E4]"><div v-for="item in data.recentRegistrations.slice(0,12)" :key="item.id" class="py-3"><div class="flex justify-between gap-3"><p class="font-semibold">{{item.child.firstName}} {{item.child.lastName}}</p><span class="text-xs text-[#6B655D]">{{dateLabel(item.registrationDate)}}</span></div><p class="text-sm text-[#6B655D]">{{item.movement.name}} · {{item.status}}</p></div></div></article><article class="border border-[#C2BAB0] bg-white p-5"><h2 class="page-title text-2xl text-[#14345E]">Paiements récents</h2><div v-if="!data.recentPayments.length" class="mt-5 text-sm text-[#6B655D]">Aucun paiement sur la période.</div><div v-else class="mt-4 divide-y divide-[#EDE9E4]"><div v-for="item in data.recentPayments.slice(0,12)" :key="item.id" class="py-3 flex justify-between gap-3"><div><p class="font-semibold">{{item.registration?.movement?.name || 'Mouvement'}}</p><p class="text-xs text-[#6B655D]">{{item.method}} · {{item.status}}</p></div><span class="font-semibold whitespace-nowrap">{{new Intl.NumberFormat('fr-FR').format(Number(item.amount))}} FCFA</span></div></div></article></div>
</template></section>
</template>